apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-a
  labels:
    app: mf-a
    tier: microfrontend
    framework: angular
    scenario: module-federation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mf-a
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mf-a
        tier: microfrontend
        framework: angular
        scenario: module-federation
    spec:
      restartPolicy: Always
      containers:
        - name: mf-a
          image: mf-a-mf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4201
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 4201
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 4201
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
