apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-a
  namespace: single-spa-experiment
  labels:
    app: mf-a
    orchestrator: single-spa
    experiment: microfrontend-study
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mf-a
      orchestrator: single-spa
      experiment: microfrontend-study
  template:
    metadata:
      labels:
        app: mf-a
        orchestrator: single-spa
        experiment: microfrontend-study
    spec:
      restartPolicy: Always
      containers:
        - name: mf-a
          image: mf-a:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4201
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 4201
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4201
            initialDelaySeconds: 15
            periodSeconds: 20
